DEVICE_PACKAGE_OVERLAYS += device/intel/cherrytrail/cht_vr/overlay

# add ifwi for cht_vr rvp, so we can share the same target for ffd/rvp
#IFWI_RVP_BIN := $(subst cht_hr,cht_hr_rvp,$(EFI_IFWI_BIN))
#BOARD_FLASHFILES += $(IFWI_RVP_BIN):ifwi_rvp.bin

# ----------------- BEGIN MIX-IN DEFINITIONS -----------------
# Mix-In definitions are auto-generated by mixin-update
##############################################################
# Source: device/intel/mixins/groups/boot-arch/efi/BoardConfig.mk
##############################################################
#
# -- OTA RELATED DEFINES --
#

# tell build system where to get the recovery.fstab. Userfastboot
# uses this too.
TARGET_RECOVERY_FSTAB ?= $(TARGET_DEVICE_DIR)/fstab

# Used by ota_from_target_files to add platform-specific directives
# to the OTA updater scripts
TARGET_RELEASETOOLS_EXTENSIONS ?= device/intel/common/recovery

# Adds edify commands swap_entries and copy_partition for robust
# update of the EFI system partition
TARGET_RECOVERY_UPDATER_LIBS := libupdater_esp

# Extra libraries needed to be rolled into recovery updater
# libgpt_static and libefivar are needed by libupdater_esp
TARGET_RECOVERY_UPDATER_EXTRA_LIBS := libcommon_recovery libgpt_static libefivar

# By default recovery minui expects RGBA framebuffer
# also affects UI in Userfastboot
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"


#
# FILESYSTEMS
#

# NOTE: These values must be kept in sync with BOARD_GPT_INI
BOARD_SYSTEMIMAGE_PARTITION_SIZE ?= 2684354560
BOARD_BOOTLOADER_PARTITION_SIZE ?= 62914560
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_CACHEIMAGE_PARTITION_SIZE ?= 104857600

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_FLASH_BLOCK_SIZE := 512
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := false

# Partition table configuration file
BOARD_GPT_INI ?= $(TARGET_DEVICE_DIR)/gpt.ini

TARGET_BOOTLOADER_BOARD_NAME := $(TARGET_DEVICE)

#
# Trusted Factory Reset - persistent partition
#
DEVICE_PACKAGE_OVERLAYS += device/intel/common/boot/overlay
ADDITIONAL_DEFAULT_PROPERTIES += ro.frp.pst=/dev/block/by-name/android_persistent

# For fastboot-uefi we need to parse gpt.ini into
# a binary format.

#can't use := here, as PRODUCT_OUT is not defined yet
BOARD_GPT_BIN = $(PRODUCT_OUT)/gpt.bin
BOARD_FLASHFILES += $(BOARD_GPT_BIN):gpt.bin
INSTALLED_RADIOIMAGE_TARGET += $(BOARD_GPT_BIN)

# For fastboot-uefi we offer the possibility to flash from a USB
# storage device using the "installer" EFI application
BOARD_FLASHFILES += $(PRODUCT_OUT)/efi/installer.efi
BOARD_FLASHFILES += device/intel/common/boot/startup.nsh


ifneq ($(EFI_EMMC_BIN),)
BOARD_FLASHFILES += $(EFI_EMMC_BIN):firmware.bin
endif

ifneq ($(EFI_IFWI_BIN),)
BOARD_FLASHFILES += $(EFI_IFWI_BIN):ifwi.bin
endif

ifneq ($(EFI_AFU_BIN),)
BOARD_FLASHFILES += $(EFI_AFU_BIN):afu.bin
endif

ifneq ($(EFI_IFWI_DEBUG_BIN),)
BOARD_FLASHFILES += $(EFI_IFWI_DEBUG_BIN):ifwi_debug.bin
endif

ifneq ($(DNXP_BIN),)
BOARD_FLASHFILES += $(DNXP_BIN):dnxp_0x1.bin
endif

ifneq ($(CFGPART_XML),)
BOARD_FLASHFILES += $(CFGPART_XML):cfgpart.xml
endif

ifneq ($(CSE_SPI_BIN),)
BOARD_FLASHFILES += $(CSE_SPI_BIN):cse_spi.bin
endif
BOOTLOADER_POLICY_OEMVARS = $(PRODUCT_OUT)/bootloader_policy-oemvars.txt
BOARD_FLASHFILES += $(BOOTLOADER_POLICY_OEMVARS):bootloader_policy-oemvars.txt
BOARD_OEM_VARS += $(BOOTLOADER_POLICY_OEMVARS)
##############################################################
# Source: device/intel/mixins/groups/config-partition/enabled/BoardConfig.mk
##############################################################
BOARD_CONFIGIMAGE_PARTITION_SIZE := 8388608
#BOARD_SEPOLICY_M4DEFS += module_config_partition=true
#BOARD_SEPOLICY_DIRS += device/intel/sepolicy/config-partition
##############################################################
# Source: device/intel/mixins/groups/kernel/gmin64/BoardConfig.mk.1
##############################################################
TARGET_USES_64_BIT_BINDER := true
##############################################################
# Source: device/intel/mixins/groups/kernel/gmin64/BoardConfig.mk
##############################################################
# Specify location of board-specific kernel headers
TARGET_BOARD_KERNEL_HEADERS := device/intel/cht-kernel/kernel-headers

KERNEL_LOGLEVEL ?= 5

BOARD_KERNEL_CMDLINE += \
        loglevel=$(KERNEL_LOGLEVEL) \
        androidboot.hardware=$(TARGET_DEVICE)\
        firmware_class.path=/system/etc/firmware

BOARD_KERNEL_CMDLINE += \
        bootboost=1

BOARD_KERNEL_CMDLINE += \
        pm_suspend_debug=1
BOARD_KERNEL_CMDLINE += \
        memmap=4M\$$0x5c400000
BOARD_KERNEL_CMDLINE += \
	intel_pstate=disable

##############################################################
# Source: device/intel/mixins/groups/sepolicy/intel/BoardConfig.mk
##############################################################
# SELinux Policy
BOARD_SEPOLICY_DIRS += device/intel/sepolicy
##############################################################
# Source: device/intel/mixins/groups/display-density/280/BoardConfig.mk
##############################################################
ADDITIONAL_DEFAULT_PROPERTIES += ro.sf.lcd_density=280

##############################################################
# Source: device/intel/mixins/groups/cpu-arch/slm/BoardConfig.mk.1
##############################################################
ifeq ($(BOARD_USE_64BIT_USERSPACE),true)
# 64b-specific items:
TARGET_ARCH := x86_64
TARGET_CPU_ABI := x86_64
TARGET_2ND_CPU_ABI := x86
TARGET_2ND_ARCH := x86
TARGET_2ND_ARCH_VARIANT := silvermont
else
# 32b-specific items:
TARGET_ARCH := x86
TARGET_CPU_ABI := x86
endif
##############################################################
# Source: device/intel/mixins/groups/cpu-arch/slm/BoardConfig.mk
##############################################################
# Items that are common between slm 32b and 64b:
TARGET_CPU_ABI_LIST_32_BIT := x86
TARGET_ARCH_VARIANT := silvermont
TARGET_CPU_SMP := true
##############################################################
# Source: device/intel/mixins/groups/houdini/true/BoardConfig.mk
##############################################################
# Install Native Bridge
ifeq ($(WITH_NATIVE_BRIDGE),true)

# Enable ARM codegen for x86 with Native Bridge
BUILD_ARM_FOR_X86 := true

# Native Bridge ABI List
NB_ABI_LIST_32_BIT := armeabi-v7a armeabi
NB_ABI_LIST_64_BIT := arm64-v8a

# Support 64 Bit Apps
ifeq ($(TARGET_SUPPORTS_64_BIT_APPS),true)
  TARGET_CPU_ABI_LIST_64_BIT ?= $(TARGET_CPU_ABI) $(TARGET_CPU_ABI2)
  ifeq ($(TARGET_SUPPORTS_32_BIT_APPS),true)
    TARGET_CPU_ABI_LIST_32_BIT ?= $(TARGET_2ND_CPU_ABI) $(TARGET_2ND_CPU_ABI2)
  endif
  ifneq ($(findstring ro.zygote=zygote32_64,$(PRODUCT_DEFAULT_PROPERTY_OVERRIDES)),)
    TARGET_CPU_ABI_LIST := \
        $(TARGET_CPU_ABI_LIST_32_BIT) \
        $(TARGET_CPU_ABI_LIST_64_BIT) \
        $(NB_ABI_LIST_32_BIT) \
        $(NB_ABI_LIST_64_BIT)
    TARGET_CPU_ABI_LIST_32_BIT += $(NB_ABI_LIST_32_BIT)
  else
    ifeq ($(TARGET_SUPPORTS_32_BIT_APPS),true)
      TARGET_CPU_ABI_LIST := \
          $(TARGET_CPU_ABI_LIST_64_BIT) \
          $(TARGET_CPU_ABI_LIST_32_BIT) \
          $(NB_ABI_LIST_32_BIT) \
          $(NB_ABI_LIST_64_BIT)
      TARGET_CPU_ABI_LIST_32_BIT += $(NB_ABI_LIST_32_BIT)
    else
      TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_64_BIT) $(NB_ABI_LIST_64_BIT)
    endif
  endif
  TARGET_CPU_ABI_LIST_64_BIT += $(NB_ABI_LIST_64_BIT)

else
  TARGET_CPU_ABI_LIST_32_BIT ?= $(TARGET_CPU_ABI) $(TARGET_CPU_ABI2)
  TARGET_CPU_ABI_LIST_32_BIT += $(NB_ABI_LIST_32_BIT)
  TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_32_BIT)
endif

endif
##############################################################
# Source: device/intel/mixins/groups/gms/minimal/BoardConfig.mk
##############################################################

DEVICE_PACKAGE_OVERLAYS += device/intel/common/gms/overlay
##############################################################
# Source: device/intel/mixins/groups/graphics/ufo_gen8/BoardConfig.mk.1
##############################################################
# Select ufo gen8 libs
UFO_ENABLE_GEN := gen8

# Defines Intel library for GPU accelerated Renderscript:
OVERRIDE_RS_DRIVER := libRSDriver_intel.so

##############################################################
# Source: device/intel/mixins/groups/graphics/ufo_gen8/BoardConfig.mk
##############################################################
BOARD_KERNEL_CMDLINE += vga=current i915.modeset=1 drm.vblankoffdelay=1 i915.fastboot=1
USE_OPENGL_RENDERER := true
USE_INTEL_UFO_DRIVER := true
USE_INTEL_UFO_OPENCL := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
INTEL_VA := true
BOARD_GRAPHIC_IS_GEN := true

# System's VSYNC phase offsets in nanoseconds
VSYNC_EVENT_PHASE_OFFSET_NS := 7500000
SF_VSYNC_EVENT_PHASE_OFFSET_NS := 5000000

# Allow HWC to perform a final CSC on virtual displays
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true

ADDITIONAL_DEFAULT_PROPERTIES += \
	ro.ufo.use_msync=1 \
	ro.ufo.use_coreu=1

BOARD_SEPOLICY_DIRS += device/intel/sepolicy/color_config
##############################################################
# Source: device/intel/mixins/groups/intel_smart_video/true/BoardConfig.mk
##############################################################
BOARD_SEPOLICY_DIRS += device/intel/sepolicy/intel_smart_video
##############################################################
# Source: device/intel/mixins/groups/storage/sdcard-mmcblk1-4xUSB-sda-emulated/BoardConfig.mk
##############################################################
DEVICE_PACKAGE_OVERLAYS += device/intel/common/storage/overlay-sdcard-usb
RECOVERY_HAVE_SD_CARD := true

##############################################################
# Source: device/intel/mixins/groups/bluetooth/bcm43340/BoardConfig.mk
##############################################################
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true
BOARD_CUSTOM_BT_CONFIG := device/intel/common/bluetooth/default/default.conf
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/intel/common/bluetooth/bcm43340/
DEVICE_PACKAGE_OVERLAYS += device/intel/common/bluetooth/overlay-bt-pan
DEVICE_PACKAGE_OVERLAYS += device/intel/common/bluetooth/overlay-hid-kb

BOARD_SEPOLICY_DIRS += device/intel/sepolicy/bluetooth/bd_prov \
                       device/intel/sepolicy/bluetooth/bcm43340

##############################################################
# Source: device/intel/mixins/groups/wlan/bcm4334x/BoardConfig.mk
##############################################################
ADDITIONAL_DEFAULT_PROPERTIES += wifi.interface=wlan0
# FIXME: use VER_0_8_X so lib_driver_cmd_bcmdhd can be built
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_HOSTAPD_PRIVATE_LIB      := lib_driver_cmd_bcmdhd
BOARD_HOSTAPD_DRIVER           := NL80211
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WLAN_DEVICE := bcmdhd
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_bcmdhd

COMBO_CHIP_VENDOR := bcm
COMBO_CHIP := bcm4334x

DEVICE_PACKAGE_OVERLAYS += device/intel/common/wlan/overlay-dual-band

WIFI_DRIVER_FW_PATH_PARAM := "/sys/module/bcmdhd/parameters/firmware_path"
WIFI_DRIVER_FW_PATH_STA := "/vendor/firmware/brcm/fw_bcm43341b0_ag.bin"
WIFI_DRIVER_FW_PATH_AP := "/vendor/firmware/brcm/fw_bcm43341b0_ag_apsta.bin"
WIFI_DRIVER_FW_PATH_P2P := "/vendor/firmware/brcm/fw_bcm43341b0_ag_p2p.bin"

DEVICE_PACKAGE_OVERLAYS += device/intel/common/wlan/overlay-pno

DEVICE_PACKAGE_OVERLAYS += device/intel/common/wlan/overlay-tcp-buffers

# Add SIM , AKA and AKA' methods in EAP entries of WiFi UI
DEVICE_PACKAGE_OVERLAYS += device/intel/common/wlan/overlay-eap-methods

# WiDi / Miracast Optimisations
DEVICE_PACKAGE_OVERLAYS += device/intel/common/wlan/overlay-miracast-go
DEVICE_PACKAGE_OVERLAYS += device/intel/common/wlan/overlay-p2p-connected-stop-scan
DEVICE_PACKAGE_OVERLAYS += device/intel/common/wlan/overlay-miracast-force-single-ch

#BOARD_SEPOLICY_DIRS += device/intel/sepolicy/wlan/bcm

##############################################################
# Source: device/intel/mixins/groups/widi/gen_sink/BoardConfig.mk.1
##############################################################
INTEL_WIDI_SINK := true

# sepolicy rules enhancement for dnsmasq for widi sink.
BOARD_SEPOLICY_DIRS += device/intel/sepolicy/widi_sink
BOARD_SEPOLICY_UNION += \
    dnsmasq.te          \
    dnsmasq_script.te   \
    file.te             \
    file_contexts

##############################################################
# Source: device/intel/mixins/groups/widi/gen_sink/BoardConfig.mk
##############################################################
# WIDI
INTEL_WIDI := true
INTEL_WIDI_GEN := true
##############################################################
# Source: device/intel/mixins/groups/aware/ish/BoardConfig.mk
##############################################################
INTEL_FEATURE_ADAPTIVE_AUTHENTICATION := true
DEVICE_PACKAGE_OVERLAYS += device/intel/common/aware/overlay
INTEL_FEATURE_AWARESERVICE := true
PRODUCT_BOOT_JARS += com.intel.aware.awareservice com.intel.aware.aaservice
##############################################################
# Source: device/intel/mixins/groups/gps/cg2k/BoardConfig.mk
##############################################################
GPS_CHIP_VENDOR := intel
GPS_CHIP := cg2000

GPS_POWER := rfkill
GPS_TRANS := ttyHSU1
GPS_CLOSE_INACTIVE := False
GPS_UART_PM := true
GPS_SIMU := False
GPS_AMIL := true
GPS_AMIL_IF := MDM
GPS_AMIL_FA_WITH_GPIO_PIN_CONTROL := true
GNSS_PULSAR := False
GPS_LPM := true

ifeq ($(GPS_LPM),true)
GNSS_LPM_EN_TCXO := true
else
GNSS_LPM_DIS_TCXO := true
endif

BOARD_SEPOLICY_DIRS += \
    device/intel/sepolicy/gps/common \
    device/intel/sepolicy/gps/cg2k

BOARD_SEPOLICY_M4DEFS += sepolicy_module_gps=cg2k \
    gps_cg2k_trans=/dev/ttyHSU1
##############################################################
# Source: device/intel/mixins/groups/audio/cht-rt5672/BoardConfig.mk
##############################################################
DEVICE_PACKAGE_OVERLAYS += device/intel/common/audio/overlay
# Enable to use DPCM driver in audio offload HAL
MRFLD_AUDIO := true
# enable to use Audio Scalability in audio offload HAL
AUDIO_OFFLOAD_SCALABILITY := true
# - USE_INTEL_ASF_EXTRACTOR: use intel's asf_extractor lib
USE_INTEL_ASF_EXTRACTOR := true
##############################################################
# Source: device/intel/mixins/groups/media/ufo/BoardConfig.mk
##############################################################
BUILD_WITH_FULL_STAGEFRIGHT := true
INTEL_STAGEFRIGHT := true

# Settings for the Media SDK library and plug-ins:
# - USE_MEDIASDK: use Media SDK support or not
USE_MEDIASDK := true
##############################################################
# Source: device/intel/mixins/groups/media-audio/mdp/BoardConfig.mk
##############################################################
BUILD_WITH_FULL_STAGEFRIGHT := true

# Settings for the Intel-optimized codecs and plug-ins:
USE_INTEL_MDP := true

##############################################################
# Source: device/intel/mixins/groups/media-misc/enabled/BoardConfig.mk
##############################################################
# Settings for MPEG4-ASP:
# - USE_INTEL_ASF_EXTRACTOR: use intel's asf_extractor lib
# - USE_SW_MPEG4: use software MPEG4 decoder including ASP support
# - USE_INTEL_IPP: use IPP acceleration in decoders
# - BOARD_USES_WRS_OMXIL_CORE: load WRS omx-il core
# - BOARD_USES_MRST_OMX: load omx-component for MPEG4-ASP
USE_INTEL_ASF_EXTRACTOR := true
USE_SW_MPEG4 := true
USE_INTEL_IPP := true
BOARD_USES_WRS_OMXIL_CORE := true
BOARD_USES_MRST_OMX := true
INTEL_VA := true
##############################################################
# Source: device/intel/mixins/groups/camera/ipu2/BoardConfig.mk
##############################################################
# The make targets for both projects are identical
# (e.g. camera.gmin.so), so the Android.mk's wrap themselves in tests
# for these.  Set only one.  And we'll just ignore the inconsistent _.
USE_CAMERA_HAL2 := false
USE_CAMERA_HAL_3 := true

# BYT/CHT hardware generation, camera3hal builds different code for
# different ISPs
BOARD_CAMERA_IPU2_SUPPORT = true

# Face Engine can be either PVL or IA.
BOARD_CAMERA_FACE_ENGINE = PVL

# camera3hal won't build if this isn't true
USE_SHARED_IA_FACE = true

# Intel camera extras (HDR, face detection, panorama, red-eye detection etc.).
USE_INTEL_CAMERA_EXTRAS := true

# Selects which subdirectory to pick in libmfldadvci/ia_imaging/ia_panorama/
IA_PANORAMA_VERSION := 1.0

USE_INTEL_JPEG := false
ifeq ($(UFO_ENABLE_GEN), gen8)
ifeq ($(USE_MEDIASDK), true)
# CHT/GEN8 has hardware JPEG encoder via Media SDK.
USE_INTEL_JPEG := true
endif
endif

# Must be "false" (NOT simply unset!) or else lots of camera
# depencencies will remove themselves from the build...
USE_CAMERA_STUB := false

# the CHT needs to support ACC
PLATFORM_ACC_SUPPORT := true
BOARD_SEPOLICY_DIRS += device/intel/sepolicy/atomisp
# the CHT needs to support FR Service
PLATFORM_FR_SUPPORT := true
BOARD_SEPOLICY_DIRS += device/intel/sepolicy/atomisp/fr_service
##############################################################
# Source: device/intel/mixins/groups/camera-intel_sdk/enabled/BoardConfig.mk
##############################################################
ifneq ($(USE_CAMERA_HAL_3),true)
$(error Camera V3 HAL must be enabled, check camera mixin option!) 
endif

# Enable Intel camera extension.
USE_INTEL_CAMERA_EXTRAS := true

# Enable Intel camera extension.
ENABLE_INTEL_CAMERA_SDK := true
##############################################################
# Source: device/intel/mixins/groups/depth-camera/ds4/BoardConfig.mk
##############################################################
ifneq ($(USE_CAMERA_HAL_3),true)
$(error Camera V3 HAL must be enabled, check camera mixin option!)
endif

USE_CAMERA_REALSENSE := true

# Enable DS4 camera HAL support. This is built as the master/main camera HAL
# and will relay calls to camera3hal for other cameras in the system.
USE_CAMERA_DS4 := true
USE_CAMERA_DS4_FW := true

# Build camera3hal as system lib instead as camera HAL module.
USE_CAMERA_ATOMISP_EMBED := true

# Allow DSAPI access
BOARD_SEPOLICY_DIRS += device/intel/sepolicy/ds4
##############################################################
# Source: device/intel/mixins/groups/sensors/ish/BoardConfig.mk
##############################################################
# enable ish libsensorhub and ish sensor HAL
# USE_ISH_SENSOR_HAL := true

# for sensorhubd selinux policy
BOARD_SEPOLICY_DIRS += device/intel/sepolicy/sensorhub
##############################################################
# Source: device/intel/mixins/groups/ipcs/acm/BoardConfig.mk
##############################################################
BOARD_SEPOLICY_DIRS += device/intel/sepolicy/ipcs/common
BOARD_SEPOLICY_DIRS += device/intel/sepolicy/ipcs/acm
##############################################################
# Source: device/intel/mixins/groups/rservice/true/BoardConfig.mk
##############################################################
BOARD_SEPOLICY_DIRS += device/intel/sepolicy/rservice
##############################################################
# Source: device/intel/mixins/groups/navigationbar/true/BoardConfig.mk
##############################################################
DEVICE_PACKAGE_OVERLAYS += device/intel/common/navigationbar/overlay

##############################################################
# Source: device/intel/mixins/groups/device-type/tablet/BoardConfig.mk
##############################################################
DEVICE_PACKAGE_OVERLAYS += device/intel/common/device-type/overlay-tablet
##############################################################
# Source: device/intel/mixins/groups/factory-scripts/true/BoardConfig.mk
##############################################################
# Include factory archive in 'make dist' output
TARGET_BUILD_INTEL_FACTORY_SCRIPTS := true

##############################################################
# Source: device/intel/mixins/groups/thermal/itux/BoardConfig.mk
##############################################################
BOARD_KERNEL_CMDLINE += thermal.off=1
##############################################################
# Source: device/intel/mixins/groups/serialport/ttyS0/BoardConfig.mk
##############################################################
BOARD_KERNEL_CMDLINE += console=ttyS0,115200n8
##############################################################
# Source: device/intel/mixins/groups/flashfiles/ini/BoardConfig.mk
##############################################################
FLASHFILES_CONFIG ?= $(TARGET_DEVICE_DIR)/flashfiles.ini
USE_INTEL_FLASHFILES := true
VARIANT_SPECIFIC_FLASHFILES ?= false

##############################################################
# Source: device/intel/mixins/groups/debug-logs/true/BoardConfig.mk
##############################################################
ifeq ($(MIXIN_DEBUG_LOGS),true)
ADDITIONAL_DEFAULT_PROPERTIES += persist.service.apklogfs.enable=1
BOARD_SEPOLICY_DIRS += device/intel/sepolicy/debug-logs
endif
##############################################################
# Source: device/intel/mixins/groups/debug-crashlogd/true/BoardConfig.mk
##############################################################
ifeq ($(MIXIN_DEBUG_LOGS),true)
BOARD_SEPOLICY_DIRS += device/intel/sepolicy/crashlogd

CRASHLOGD_LOGS_PATH := "/data/logs"
CRASHLOGD_APLOG := true
CRASHLOGD_FULL_REPORT := true
CRASHLOGD_MODULE_MODEM ?= true
CRASHLOGD_MODULE_BTDUMP := true
CRASHLOGD_USE_SD := false
endif
##############################################################
# Source: device/intel/mixins/groups/debug-coredump/true/BoardConfig.mk
##############################################################
ifeq ($(MIXIN_DEBUG_LOGS),true)
BOARD_SEPOLICY_DIRS += device/intel/sepolicy/coredump

# Enable core dump for eng builds
ifeq ($(TARGET_BUILD_VARIANT),eng)
ADDITIONAL_DEFAULT_PROPERTIES += persist.core.enabled=1
else
ADDITIONAL_DEFAULT_PROPERTIES += persist.core.enabled=0
endif
CRASHLOGD_COREDUMP := true
endif
##############################################################
# Source: device/intel/mixins/groups/libiha/true/BoardConfig.mk
##############################################################
ifneq ($(wildcard vendor/intel/PRIVATE/cert/testkey*),)
PRODUCT_DEFAULT_DEV_CERTIFICATE := vendor/intel/PRIVATE/cert/testkey
endif
BOARD_SEPOLICY_DIRS += device/intel/sepolicy/libiha
##############################################################
# Source: device/intel/mixins/groups/libhealthd/intel/BoardConfig.mk
##############################################################
BOARD_HAL_STATIC_LIBRARIES += libhealthd.intel
##############################################################
# Source: device/intel/mixins/groups/widevine/true/BoardConfig.mk
##############################################################
BOARD_USE_INTEL_OEMCRYPTO := true

ADDITIONAL_DEFAULT_PROPERTIES += \
	persist.ims_support=0 \
	persist.sys.telephony.off=1 \
	persist.tcs.sw_folder=generic_nomodem \
	ro.swconf.info=generic_nomodem

##############################################################
# Source: device/intel/mixins/groups/intel_prop/true/BoardConfig.mk
##############################################################
BOARD_SEPOLICY_DIRS += device/intel/sepolicy/intel_prop

ifneq ($(TARGET_UEFI_ARCH),)
INTEL_PROP_LIBDMI := true
endif

##############################################################
# Source: device/intel/mixins/groups/passpoint/true/BoardConfig.mk
##############################################################
#seplicy rules for passpoint
BOARD_SEPOLICY_DIRS += device/intel/sepolicy/passpoint

##############################################################
# Source: device/intel/mixins/groups/vpp/isv/BoardConfig.mk
##############################################################
# Settings for Intel Smart Video library:
TARGET_HAS_ISV := true

DEVICE_PACKAGE_OVERLAYS += device/intel/common/video_isv/overlay

ADDITIONAL_DEFAULT_PROPERTIES += \
    persist.sys.media.avsync = 1

# Settings for the video extended mode:
INTEL_FEATURE_VIDEO_EXT_MODE := true

PRODUCT_BOOT_JARS += com.intel.extmode
##############################################################
# Source: device/intel/mixins/groups/dexpreopt/disabled/BoardConfig.mk
##############################################################
# Disable dex-preoptimization.
WITH_DEXPREOPT := false
##############################################################
# Source: device/intel/mixins/groups/pstore/ram_pram/BoardConfig.mk.1
##############################################################
BOARD_KERNEL_CMDLINE += pstore.backend=ramoops
##############################################################
# Source: device/intel/mixins/groups/pstore/ram_pram/BoardConfig.mk
##############################################################
##############################################################
# Source: device/intel/mixins/groups/telephony/tablet_flashless_voice/BoardConfig.mk.1
##############################################################
# Telephony voice overlay folder
DEVICE_PACKAGE_OVERLAYS += device/intel/common/telephony/overlay_voice
##############################################################
# Source: device/intel/mixins/groups/telephony/tablet_flashless_voice/BoardConfig.mk
##############################################################
# BoardConfig.mk common to all platforms with Telephony

# Config flags
BOARD_HAVE_MODEM := false
BOARD_HAVE_ATPROXY := false
# crashlogd configuration
#CRASHLOGD_MODULE_MODEM ?= true
##############################################################
# Source: device/intel/mixins/groups/manufacturing-data/enabled/BoardConfig.mk
##############################################################
BOARD_GPT_MFG_INI ?= $(TARGET_DEVICE_DIR)/gpt-mfg.ini

BOARD_GPT_MFG_BIN = $(PRODUCT_OUT)/gpt-mfg.bin
##############################################################
# Source: device/intel/mixins/groups/cellcoex/true/BoardConfig.mk
##############################################################
BOARD_HAVE_CELLCOEX := true
BOARD_HAVE_CELLCOEX_APK := true

# Enable core dump for eng and userdebug builds
ifneq ($(TARGET_BUILD_VARIANT),user)
    # Verbose level of the service.
    ADDITIONAL_DEFAULT_PROPERTIES += log.tag.CWS_CELLCOEX_MGR=DEBUG
    # Verbose level of the coexistence plugin.
    ADDITIONAL_DEFAULT_PROPERTIES += log.tag.CWS_CELLCOEX_HANDLER=DEBUG
endif

# Enable geolocation feature
ADDITIONAL_DEFAULT_PROPERTIES += persist.cellcoex.geoloc=1

# sepolicy rules enhancement for cellcoex
BOARD_SEPOLICY_DIRS += device/intel/common/sepolicy/cellcoex/in_system_apk
BOARD_SEPOLICY_UNION += \
    hostapd.te \
    service.te \
    service_contexts \
    system_app.te \
    wpa.te
##############################################################
# Source: device/intel/mixins/groups/videocme/gen/BoardConfig.mk
##############################################################
# WebRTC
ENABLE_WEBRTC := true
WEBRTC_GEN := true
#enable compilation of cve video
ENABLE_IR94 := true
#enable compilation of vcme for RCS video sharing
ENABLE_VSH := true
##############################################################
# Source: device/intel/mixins/groups/2ndstage/oemvars/BoardConfig.mk
##############################################################
TARGET_BOOTLOADER_IS_2ND := true
BOARD_OEM_VARS += $(TARGET_DEVICE_DIR)/oemvars.txt
##############################################################
# Source: device/intel/mixins/groups/autodetect/default/BoardConfig.mk
##############################################################
BOARD_SEPOLICY_DIRS += device/intel/sepolicy/autodetect/false
##############################################################
# Source: device/intel/mixins/groups/feature_config/default/BoardConfig.mk
##############################################################
PRODUCT_BOOT_JARS += com.intel.config


##############################################################
# Source: device/intel/mixins/groups/mixin-check/default/BoardConfig.mk
##############################################################
mixin_update := $(wildcard device/intel/mixins/mixin-update)

ifneq ($(mixin_update),)

# TARGET_DEVICE_DIR doesn't get expanded until later. so OK to reference
# this in BoardConfig.mk
.PHONY: check-mixins
check-mixins:
	device/intel/mixins/mixin-update --dry-run

# This invocation of dumpvar gets called during the 'lunch' command. Hook it to
# do some additional checking.
dumpvar-TARGET_DEVICE: check-mixins
droidcore: check-mixins

endif

# ------------------ END MIX-IN DEFINITIONS ------------------
#replace TARGET_BOOTLOADER_BOARD_NAME
TARGET_BOOTLOADER_BOARD_NAME := cht_rvp
