# FIXME surfaceflinger explodes if this is not "gmin"
TARGET_BOARD_PLATFORM := gmin

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/init.rc:root/init.cht_vr.rc \
    $(LOCAL_PATH)/init.recovery.rc:root/init.recovery.cht_vr.rc \
    $(LOCAL_PATH)/ueventd.rc:root/ueventd.cht_vr.rc \
    $(LOCAL_PATH)/fstab:root/fstab

# These files are extremely board-specific and doesn't go in the mix-in
PRODUCT_COPY_FILES += \
    frameworks/av/media/libstagefright/data/media_codecs_google_audio.xml:system/etc/media_codecs_google_audio.xml \
    frameworks/av/media/libstagefright/data/media_codecs_google_video.xml:system/etc/media_codecs_google_video.xml \
    $(LOCAL_PATH)/camera_profiles.xml:system/etc/camera_profiles.xml \
    $(LOCAL_PATH)/media_profiles.xml:system/etc/media_profiles.xml \
    $(LOCAL_PATH)/../media_codecs.xml:system/etc/media_codecs.xml \
    $(LOCAL_PATH)/../video_isv_profile.xml:system/etc/video_isv_profile.xml \

# Sensor Calibration tool
PRODUCT_PACKAGES += \
	libsensorcalitool
# Camera: Device-specific configuration files.
PRODUCT_PACKAGES += \
    camera3_profiles.xml

PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.camera.flash-autofocus.xml:system/etc/permissions/android.hardware.camera.flash-autofocus.xml \
    frameworks/native/data/etc/android.hardware.camera.front.xml:system/etc/permissions/android.hardware.camera.front.xml \
    frameworks/native/data/etc/android.hardware.camera.manual_postprocessing.xml:system/etc/permissions/android.hardware.camera.manual_postprocessing.xml \
    frameworks/native/data/etc/android.hardware.camera.manual_sensor.xml:system/etc/permissions/android.hardware.camera.manual_sensor.xml

# Camera: Board-specific kernel module initialization script.
PRODUCT_COPY_FILES += $(LOCAL_PATH)/init.atomisp.sh:system/etc/init.atomisp.sh

PRODUCT_COPY_FILES += vendor/intel/hardware/ish-sensors/vr_sensors/sensor_hal_config_default.xml:system/etc/sensor_hal_config_default.xml

PRODUCT_COPY_FILES += $(LOCAL_PATH)/sensorhub_fw_upgrade.sh:system/bin/sensorhub_fw_upgrade.sh
PRODUCT_COPY_FILES += vendor/intel/fw/sensorhub/stm32flash:system/bin/stm32flash
PRODUCT_COPY_FILES += vendor/intel/fw/sensorhub/sensorhub.bin:system/etc/sensorhub.bin

PRODUCT_COPY_FILES += device/intel/cherrytrail/cht_vr/sh_version.sh:system/bin/sh_version.sh

# Audio package
PRODUCT_PACKAGES += meta.package.audio

PRODUCT_PROPERTY_OVERRIDES += sys.powerctl.no.shutdown = 1

# ----------------- BEGIN MIX-IN DEFINITIONS -----------------
# Mix-In definitions are auto-generated by mixin-update
##############################################################
# Source: device/intel/mixins/groups/boot-arch/efi/product.mk
##############################################################
TARGET_UEFI_ARCH := x86_64
BIOS_VARIANT := release

$(call inherit-product,build/target/product/verity.mk)

PRODUCT_SYSTEM_VERITY_PARTITION := /dev/block/by-name/android_system

PRODUCT_COPY_FILES += \
	frameworks/native/data/etc/android.software.verified_boot.xml:system/etc/permissions/android.software.verified_boot.xml

BOARD_SFU_UPDATE := hardware/intel/efi_capsules/$(BIOS_VARIANT)/$(TARGET_PRODUCT).fv
EFI_IFWI_BIN := hardware/intel/efi_capsules/$(BIOS_VARIANT)/$(TARGET_PRODUCT)_ifwi.bin
EFI_EMMC_BIN := hardware/intel/efi_capsules/$(BIOS_VARIANT)/$(TARGET_PRODUCT)_emmc.bin
EFI_AFU_BIN := hardware/intel/efi_capsules/$(BIOS_VARIANT)/$(TARGET_PRODUCT)_afu.bin
DNXP_BIN := hardware/intel/efi_capsules/$(BIOS_VARIANT)/$(TARGET_PRODUCT)_dnxp_0x1.bin
CFGPART_XML := hardware/intel/efi_capsules/$(BIOS_VARIANT)/$(TARGET_PRODUCT)_cfgpart.xml
CSE_SPI_BIN := hardware/intel/efi_capsules/$(BIOS_VARIANT)/$(TARGET_PRODUCT)_cse_spi.bin

ifneq ($(TARGET_BUILD_VARIANT),user)
# Allow to add debug ifwi file only on userdebug and eng flashfiles
EFI_IFWI_DEBUG_BIN := hardware/intel/efi_capsules/debug/$(TARGET_PRODUCT)_ifwi.bin
endif

ifneq ($(CALLED_FROM_SETUP),true)
ifeq ($(wildcard $(BOARD_SFU_UPDATE)),)
$(warning $(BOARD_SFU_UPDATE) not found, OTA updates will not provide a firmware capsule)
BOARD_SFU_UPDATE :=
endif
ifeq ($(wildcard $(EFI_EMMC_BIN)),)
$(warning $(EFI_EMMC_BIN) not found, flashfiles will not include 2nd stage EMMC firmware)
EFI_EMMC_BIN :=
endif
ifeq ($(wildcard $(EFI_IFWI_BIN)),)
$(warning $(EFI_IFWI_BIN) not found, IFWI binary will not be provided in out/dist/)
EFI_IFWI_BIN :=
endif
ifeq ($(wildcard $(EFI_AFU_BIN)),)
$(warning $(EFI_AFU_BIN) not found, IFWI binary will not be provided in out/dist/)
EFI_AFU_BIN :=
endif
ifeq ($(wildcard $(EFI_IFWI_DEBUG_BIN)),)
EFI_IFWI_DEBUG_BIN :=
endif
ifeq ($(wildcard $(DNXP_BIN)),)
DNXP_BIN :=
endif
ifeq ($(wildcard $(CFGPART_XML)),)
CFGPART_XML :=
endif
ifeq ($(wildcard $(CSE_SPI_BIN)),)
CSE_SPI_BIN :=
endif
endif
# Allow Kernelflinger to use the power key as an input source.
# Doesn't work on most boards.
KERNELFLINGER_USE_POWER_BUTTON := true
# Allow Kernelflinger to start watchdog prior to boot the kernel
KERNELFLINGER_USE_WATCHDOG := true
# Allow Kernelflinger to use the non-standard ChargingApplet protocol
# to get battery and charger status and modify the boot flow in
# consequence.
KERNELFLINGER_USE_CHARGING_APPLET := true
# It makes kernelflinger relies on the BOOTLOADER POLICY EFI
# variables.  TARGET_BOOTLOADER_POLICY is the desired bitmask for this
# device.
# - 0x0000000000000000: no policy, the device behaves as usual
# - 0x0000000000000001: unlock is totally prohibited on this device.
#   The only way to unlock is to use the secured force-unlock
#   mechasnism.
# If TARGET_BOOTLOADER_POLICY is equal to 'external' the bootloader
# policy OEMVARS should be installed manually in
# $(BOOTLOADER_POLICY_OEMVARS).
TARGET_BOOTLOADER_POLICY := 0x0
##############################################################
# Source: device/intel/mixins/groups/kernel/gmin64/product.mk.1
##############################################################
TARGET_KERNEL_ARCH := x86_64

##############################################################
# Source: device/intel/mixins/groups/kernel/gmin64/product.mk
##############################################################
# FIXME: Modules are copied twice in the system
# - as a flat directory where all modules are. This is the method that android's insmod is expecting modules to be
# - as a tree of modules as output by the kernel build system. This is the way hald's libkmod is expecting modules to be
# on binary kernel directories/artifactory tarballs, flat directory is stored in $(ARCH)/modules, while tree directory is stored in $(ARCH)/lib/modules
# both directories contain same data


ifneq ($(TARGET_BUILD_VARIANT),user)
  KERNEL_MODULES_ROOT := root/lib/modules
  ADDITIONAL_DEFAULT_PROPERTIES += ro.boot.moduleslocation=/lib/modules
else
  KERNEL_MODULES_ROOT := system/lib/modules
  ADDITIONAL_DEFAULT_PROPERTIES += ro.boot.moduleslocation=/system/lib/modules
endif

##############################################################
# Source: device/intel/mixins/groups/dalvik-heap/tablet-7in-hdpi-1024/product.mk
##############################################################
#include frameworks/native/build/tablet-7in-hdpi-1024-dalvik-heap.mk
PRODUCT_PROPERTY_OVERRIDES += \
    dalvik.vm.heapstartsize=8m \
    dalvik.vm.heapgrowthlimit=100m \
    dalvik.vm.heapsize=174m \
    dalvik.vm.heaptargetutilization=0.75 \
    dalvik.vm.heapminfree=512k \
    dalvik.vm.heapmaxfree=8m
##############################################################
# Source: device/intel/mixins/groups/houdini/true/product.mk
##############################################################
$(call inherit-product-if-exists, vendor/intel/houdini/houdini.mk)

##############################################################
# Source: device/intel/mixins/groups/gms/minimal/product.mk.1
##############################################################
FLAG_GMS_PACKAGES := minimal
##############################################################
# Source: device/intel/mixins/groups/gms/minimal/product.mk
##############################################################
FLAG_GMS_AVAILABLE := yes
$(call inherit-product-if-exists, vendor/google/gms/products/intel_gms.mk)
##############################################################
# Source: device/intel/mixins/groups/graphics/ufo_gen8/product.mk
##############################################################
#
# Hardware Accelerated Graphics
#
PRODUCT_PACKAGES += \
    libdrm \
    libdrm_intel \

#
# Color conversion library
#
PRODUCT_PACKAGES += \
    libI420colorconvert

ifneq ($(BOARD_HAVE_GEN_GFX_SRC),true)
    # UFO prebuilts
    PRODUCT_PACKAGES += ufo_prebuilts
    ifneq ($(TARGET_2ND_ARCH),)
        PRODUCT_PACKAGES += ufo_prebuilts_32
    endif

else # ufo packages when building from source
    PRODUCT_PACKAGES += ufo
    PRODUCT_PACKAGES += ufo_test
endif

PRODUCT_PROPERTY_OVERRIDES += ro.opengles.version = 196609

##############################################################
# Source: device/intel/mixins/groups/ethernet/dhcp/product.mk
##############################################################
PRODUCT_COPY_FILES += \
        frameworks/native/data/etc/android.hardware.ethernet.xml:system/etc/permissions/android.hardware.ethernet.xml
##############################################################
# Source: device/intel/mixins/groups/rfkill/true/product.mk
##############################################################
PRODUCT_COPY_FILES += device/intel/common/rfkill/rfkill-init.sh:system/bin/rfkill-init.sh
##############################################################
# Source: device/intel/mixins/groups/bluetooth/bcm43340/product.mk
##############################################################
PRODUCT_PACKAGES += \
    bd_prov \
    libbt-vendor \
    rfkill_bt.sh \
    bt_vendor.default.conf \
    audio.a2dp.default \
    bt_bcm43340 \

PRODUCT_COPY_FILES += frameworks/native/data/etc/android.hardware.bluetooth.xml:system/etc/permissions/android.hardware.bluetooth.xml \
		frameworks/native/data/etc/android.hardware.bluetooth_le.xml:system/etc/permissions/android.hardware.bluetooth_le.xml

##############################################################
# Source: device/intel/mixins/groups/wlan/bcm4334x/product.mk
##############################################################
PRODUCT_COPY_FILES += \
    device/intel/common/wlan/wpa_supplicant-common.conf:system/etc/wifi/wpa_supplicant.conf \
    device/intel/common/wlan/bcm4334x/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf \
    device/intel/common/wlan/hostapd.conf:system/etc/wifi/hostapd.conf \
    frameworks/native/data/etc/android.hardware.wifi.xml:system/etc/permissions/android.hardware.wifi.xml \
    frameworks/native/data/etc/android.hardware.wifi.direct.xml:system/etc/permissions/android.hardware.wifi.direct.xml

PRODUCT_PACKAGES += wpa_supplicant \
    hostapd \
    wlan_prov \
    fw_bcm43341b0_ag.bin \
    fw_bcm43341b0_ag_apsta.bin \
    fw_bcm43341b0_ag_p2p.bin \
    nvram_ap6234.txt

PRODUCT_PACKAGES_DEBUG += dhdutil_1.201.90
##############################################################
# Source: device/intel/mixins/groups/widi/gen_sink/product.mk.1
##############################################################

# Script required when WiDi SINK is P2P Group Owner.
PRODUCT_PACKAGES += dhcp_lease_evt.sh
##############################################################
# Source: device/intel/mixins/groups/widi/gen_sink/product.mk
##############################################################
#widi
PRODUCT_PACKAGES += widi
PRODUCT_PACKAGES += widi_sink
##############################################################
# Source: device/intel/mixins/groups/aware/ish/product.mk
##############################################################
# AA
PRODUCT_PACKAGES += \
    aware_bundle \
    adaptive_authentication \
    libaware_client \
    com.intel.aware.aaservice


# Aware HAL
PRODUCT_PACKAGES += \
    aware.primary.$(TARGET_PRODUCT)
##############################################################
# Source: device/intel/mixins/groups/wfa-sigma/sigma_gen/product.mk
##############################################################
#sigma_c
ifneq (,$(filter $(TARGET_BUILD_VARIANT),eng userdebug))
PRODUCT_PACKAGES += \
wifi_wfa \
hostapd_cli \
wpa_cli
endif

#sigma_java
PRODUCT_PACKAGES_DEBUG += \
SigmaCapiUI \
com.intel.sigma.sigmaapi \
com.intel.sigma.sigmaapi.xml \
libsigmajni \
libsigmacapi \
shcli \
shsrv \
intel_sigma
# Build only when INTEL_PASSPOINT is NOT set
ifneq ($(INTEL_PASSPOINT), true)
PRODUCT_PACKAGES_DEBUG += \
com.intel.passpointmanager \
sigmapasspointmanager_stub
endif
# Build only when INTEL_WIDI_SINK is NOT set
ifneq ($(INTEL_WIDI_SINK), true)
PRODUCT_PACKAGES_DEBUG += \
com.intel.widi.sink \
sigmawidisink_stub
endif
##############################################################
# Source: device/intel/mixins/groups/gps/cg2k/product.mk
##############################################################
PRODUCT_PACKAGES += \
    cws_manu \
    gps.$(TARGET_BOARD_PLATFORM) \
    gnssCG2000 \
    libgnssconf \
    libgnsspatch \
    libgnssapi \
    gnssStelp \
    RXN_IntApp \
    MSLConfig.txt \
    libgnssrxnkey \
    rxn_services_xybrid

PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.location.gps.xml:system/etc/permissions/android.hardware.location.gps.xml \
##############################################################
# Source: device/intel/mixins/groups/audio/cht-rt5672/product.mk
##############################################################
# Tinyalsa
PRODUCT_PACKAGES_DEBUG += \
         tinymix \
         tinyplay \
         tinycap \
         tinyprobe

# SST Firmware
PRODUCT_PACKAGES += \
    fw_sst_22a8.bin \
    dfw_sst.bin

#audio FWDT Library for asoc_dfw
PRODUCT_PACKAGES += \
    dfw_sst.v1

# Ring 1 audio policy configuration file
PRODUCT_COPY_FILES += $(LOCAL_PATH)/audio/audio_policy.conf:system/etc/audio_policy.conf

#Build OMX wrapper codecs for wma
PRODUCT_PACKAGES += \
    libstagefright_soft_wmadec_mdp
    

# for Pfw Client Simulator
PRODUCT_PACKAGES_DEBUG += \
    audio_correlation_tool \
    test-platform
##############################################################
# Source: device/intel/mixins/groups/media/ufo/product.mk
##############################################################
# libstagefrighthw
BUILD_WITH_FULL_STAGEFRIGHT := true
PRODUCT_PACKAGES += \
    libstagefrighthw

# Media SDK and OMX IL components
PRODUCT_PACKAGES += \
    libmfxhw32 \
    libmfxsw32 \
    libmfx_omx_core \
    libmfx_omx_components_hw \
    libmfx_omx_components_sw \
    libgabi++-mfx \
    libstlport-mfx
##############################################################
# Source: device/intel/mixins/groups/media-audio/mdp/product.mk
##############################################################
# libstagefrighthw
PRODUCT_PACKAGES += \
    libstagefrighthw

# Build OMX wrapper codecs
PRODUCT_PACKAGES += \
    libmdp_omx_core \
    libstagefright_soft_mp3dec_mdp \
    libstagefright_soft_aacdec_mdp \
    libstagefright_soft_aacenc_mdp \
    libstagefright_soft_vorbisdec_mdp \
    libstagefright_soft_amrenc_mdp \
    libstagefright_soft_amrdec_mdp

##############################################################
# Source: device/intel/mixins/groups/media-misc/enabled/product.mk
##############################################################
# Decoding MPEG4-ASP/H263
PRODUCT_PACKAGES += \
	libasfparser \
	libmixvbp \
	libmixvbp_mpeg4 \
	libva_videodecoder \
	libOMXVideoDecoderMPEG4 \
	libOMXVideoDecoderH263 \
	libva_videoencoder \
	libOMXVideoEncoderMPEG4 \
	libOMXVideoEncoderH263 \
	libintelmetadatabuffer \
	libwrs_omxil_core_pvwrapped \
	libwrs_omxil_base

# Copy config files to system
PRODUCT_COPY_FILES += device/intel/common/media/wrs_omxil_components.list:system/etc/wrs_omxil_components.list
##############################################################
# Source: device/intel/mixins/groups/camera/ipu2/product.mk.1
##############################################################
# Camera: Platform-specific ISP firmware.
PRODUCT_PACKAGES += \
    shisp_2401a0_v21.bin
##############################################################
# Source: device/intel/mixins/groups/camera/ipu2/product.mk
##############################################################
ifeq ($(TARGET_BOARD_PLATFORM),)
    $(error Please define TARGET_BOARD_PLATFORM in product-level Makefile)
endif

# Camera HAL (camera3hal).
PRODUCT_PACKAGES += camera.$(TARGET_BOARD_PLATFORM)

# 3A/AIQ and camera tuning files.
PRODUCT_PACKAGES += \
    libmfldadvci \
    dummy.aiqb

# Acc service and client
PRODUCT_PACKAGES += \
    libacc_service \
    libacc_client

# Acc SDK
PRODUCT_PACKAGES += \
    com.intel.acc.extensions \
    com.intel.acc.extensions.xml \
    libacc_jni

# Acc SDK test App
PRODUCT_PACKAGES_DEBUG += \
    AppAccTest

# Camera ISP Firmware
PRODUCT_PACKAGES += \
    hdr_v2_fw_css21_2401 \
    ull_v15_fw_css21_2401

# Fr service and client
PRODUCT_PACKAGES += \
    libfr_service \
    libfr_client \
# Only include test apps in eng builds.
PRODUCT_PACKAGES_ENG += \
    TestingCamera \
    TestingCamera2
##############################################################
# Source: device/intel/mixins/groups/camera-refcam/enabled/product.mk
##############################################################
# Refcam
PRODUCT_PACKAGES_DEBUG += \
	android-support-test \
	RefCam1 \
	RefCam2 \
	RefCam1Tests
##############################################################
# Source: device/intel/mixins/groups/camera-intel_sdk/enabled/product.mk
##############################################################
# The Intel camera2 SDK exposes Intel extensions to the camera2 API.
# These are exposed in a Google defined way that avoids modifying
# any AOSP code. Use "make docs" to generate it; the output will be located at
# "out/target/common/docs/camera2sdk_doc".
PRODUCT_PACKAGES += \
	com.intel.camera2.extensions \
	com.intel.camera2.extensions.xml \
	libiacp_jni \
	libpvl_jni \
	libpvl_panorama_jni \
	libpvl_skin_smoothing_jni
##############################################################
# Source: device/intel/mixins/groups/depth-camera/ds4/product.mk
##############################################################
# DS4 HAL modules.
PRODUCT_PACKAGES += \
	camera.$(TARGET_BOARD_PLATFORM) \
	camera.plugin.ds4.$(TARGET_BOARD_PLATFORM)

# DS4 FW.
PRODUCT_PACKAGES += \
	ds4fw

# DS4 camera2 API extensions.
PRODUCT_PACKAGES += \
	com.intel.camera2.extensions.depthcamera \
	com.intel.camera2.extensions.depthcamera.xml \
	libinteldepthcamera_jni

# DS4 FW Update Tool.
PRODUCT_PACKAGES += \
       FWUpdateR200

# DSAPI property default value
PRODUCT_PROPERTY_OVERRIDES += \
	sys.ds4.claim_gpio=0

# Apps can now be compiled against the add-on without having to
# manually copy the com.intel.camera2.extensions.depthcamera.jar to the
# app 'libs' folder, ensuring only the built-in jar file
# on the device is used.
PRODUCT_BOOT_JARS += com.intel.camera2.extensions.depthcamera

# Product configuration files.
PRODUCT_COPY_FILES += \
	device/intel/common/camera/ds4/camera_realsense.xml:system/etc/camera_realsense.xml \
	device/intel/common/camera/ds4/com.intel.camera.depth.xml:system/etc/permissions/com.intel.camera.depth.xml

$(eval PRODUCT_COPY_FILES += $(LOCAL_PATH)/camera_realsense.xml:system/etc/camera_realsense.$(TARGET_BOARD_PLATFORM).xml)
##############################################################
# Source: device/intel/mixins/groups/sensors/ish/product.mk
##############################################################
# ISH sensorhubd modules
PRODUCT_PACKAGES += \
    sensorhubd      \
    libsensorhub    \
    AndroidCalibrationTool

# ISH Sensor HAL modules
PRODUCT_PACKAGES += \
    sensors.$(TARGET_BOARD_PLATFORM)

$(foreach sensor,accelerometer compass gyroscope light stepcounter stepdetector, \
$(eval PRODUCT_COPY_FILES += frameworks/native/data/etc/android.hardware.sensor.$(sensor).xml:system/etc/permissions/android.hardware.sensor.$(sensor).xml))
##############################################################
# Source: device/intel/mixins/groups/usb/host+acc/product.mk
##############################################################
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.usb.accessory.xml:system/etc/permissions/android.hardware.usb.accessory.xml \
    frameworks/native/data/etc/android.hardware.usb.host.xml:system/etc/permissions/android.hardware.usb.host.xml

# usb accessory
PRODUCT_PACKAGES += \
    com.android.future.usb.accessory

##############################################################
# Source: device/intel/mixins/groups/usb-gadget/g_android/product.mk
##############################################################
# Set default USB interface
ifeq ($(BUILD_FOR_CTS_AUTOMATION),true)
# Build for automated CTS
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += persist.sys.usb.config=mtp,adb
PRODUCT_COPY_FILES += device/intel/common/usb-gadget/adb_keys:root/adb_keys
else
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += persist.sys.usb.config=mtp
endif

# Enable Secure Debugging
ifeq ($(TARGET_BUILD_VARIANT),user)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.adb.secure=1
endif

# Add Intel adb keys for userdebug/eng builds
ifneq ($(TARGET_BUILD_VARIANT),user)
PRODUCT_COPY_FILES += device/intel/common/usb-gadget/adb_keys:root/adb_keys
endif
##############################################################
# Source: device/intel/mixins/groups/ipcs/acm/product.mk
##############################################################
# Inter Process Collaboration Service (IPCS)
PRODUCT_PACKAGES_DEBUG += \
    libipcs \
    libipcservice_tcpip_plugin \
    libipcservice_tty_plugin \
    libipcservice_uds_plugin

# IPCS daemon
PRODUCT_PACKAGES_DEBUG += \
    ipcsd

# IPCS Client program
PRODUCT_PACKAGES_DEBUG += \
    ipcs_client
##############################################################
# Source: device/intel/mixins/groups/rservice/true/product.mk
##############################################################
# WCS remoting solution for ENG and USERDEBUG
ifneq ($(TARGET_BUILD_VARIANT),user)
PRODUCT_PACKAGES += \
       rservice \
       at_cli_client
endif

##############################################################
# Source: device/intel/mixins/groups/rocs/true/product.mk
##############################################################
# WCS ROCS
ifneq ($(TARGET_BUILD_VARIANT),user)
PRODUCT_PACKAGES += \
       xvt_rocs
endif
##############################################################
# Source: device/intel/mixins/groups/touch/atmel1000/product.mk
##############################################################
PRODUCT_COPY_FILES += \
        device/intel/common/touch/ATML1000_00_4a_03EB_8C0E.idc:system/usr/idc/ATML1000_00_4a_03EB_8C0E.idc \
        device/intel/common/touch/atmel_mxt_ts.idc:system/usr/idc/atmel_mxt_ts.idc \
        frameworks/native/data/etc/android.hardware.touchscreen.multitouch.jazzhand.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml

##############################################################
# Source: device/intel/mixins/groups/device-type/tablet/product.mk
##############################################################
PRODUCT_CHARACTERISTICS := tablet

PRODUCT_COPY_FILES += \
        frameworks/native/data/etc/tablet_core_hardware.xml:system/etc/permissions/tablet_core_hardware.xml

##############################################################
# Source: device/intel/mixins/groups/debug-tools/true/product.mk
##############################################################
PRODUCT_PACKAGES_DEBUG += \
    AndroidTerm \
    libjackpal-androidterm4 \
    peeknpoke \
    toybox_bin \
    pytimechart-record
##############################################################
# Source: device/intel/mixins/groups/charger/true/product.mk
##############################################################
PRODUCT_PACKAGES += charger charger_res_images

##############################################################
# Source: device/intel/mixins/groups/thermal/itux/product.mk
##############################################################
ENABLE_ITUX := true
ITUX_ACPI_CONFIG := false
ITUX_MODEM_CTL := true
PRODUCT_PACKAGES += itux
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/config/thermal_sensor_config.xml:/system/etc/thermal_sensor_config.xml \
    $(LOCAL_PATH)/config/thermal_throttle_config.xml:/system/etc/thermal_throttle_config.xml
PRODUCT_PACKAGES += thermal_lite
##############################################################
# Source: device/intel/mixins/groups/debug-logs/true/product.mk
##############################################################
ifneq ($(TARGET_BUILD_VARIANT),user)
MIXIN_DEBUG_LOGS := true
endif

ifeq ($(MIXIN_DEBUG_LOGS),true)
PRODUCT_COPY_FILES += device/intel/common/debug/init.logs.rc:root/init.logs.rc
PRODUCT_PACKAGES += \
    logcatext \
    elogs.sh \
    start_log_srv.sh \
    logcat_ep.sh
endif
##############################################################
# Source: device/intel/mixins/groups/debug-crashlogd/true/product.mk
##############################################################
ifeq ($(MIXIN_DEBUG_LOGS),true)
PRODUCT_COPY_FILES += \
	device/intel/common/debug/init.crashlogd.rc:root/init.crashlogd.rc \
	$(call add-to-product-copy-files-if-exists,$(LOCAL_PATH)/../ingredients.conf:system/etc/ingredients.conf)
PRODUCT_PACKAGES += crashlogd \
	dumpstate_dropbox.sh
endif
##############################################################
# Source: device/intel/mixins/groups/debug-coredump/true/product.mk
##############################################################
ifeq ($(MIXIN_DEBUG_LOGS),true)
PRODUCT_COPY_FILES += device/intel/common/debug/init.coredump.rc:root/init.coredump.rc
endif
##############################################################
# Source: device/intel/mixins/groups/debug-phonedoctor/true/product.mk
##############################################################
ifeq ($(MIXIN_DEBUG_LOGS),true)
PRODUCT_PACKAGES += crash_package
endif
##############################################################
# Source: device/intel/mixins/groups/debug-charging/true/product.mk
##############################################################
# make console and adb available in charging mode for eng and userdebug builds
ifneq ($(TARGET_BUILD_VARIANT),user)
PRODUCT_COPY_FILES += device/intel/common/debug/init.debug-charging.rc:root/init.debug-charging.rc
endif
##############################################################
# Source: device/intel/mixins/groups/debug-mpm/true/product.mk
##############################################################
# Enable MPM for eng and userdebug builds
ifneq ($(TARGET_BUILD_VARIANT),user)
PRODUCT_COPY_FILES += device/intel/common/debug/init.diag.rc:root/init.diag.rc
PRODUCT_PACKAGES += MPMApp
endif
##############################################################
# Source: device/intel/mixins/groups/debug-lmdump/true/product.mk
##############################################################
ifneq ($(TARGET_BUILD_VARIANT),user)
PRODUCT_COPY_FILES += device/intel/common/debug/init.lmdump.rc:root/init.lmdump.rc
endif
##############################################################
# Source: device/intel/mixins/groups/lights/true/product.mk
##############################################################
# Lights HAL
PRODUCT_PACKAGES += lights.$(TARGET_BOARD_PLATFORM)

##############################################################
# Source: device/intel/mixins/groups/power/true/product.mk
##############################################################
# Power HAL
PRODUCT_PACKAGES += power.$(TARGET_BOARD_PLATFORM) \
                    power_hal_helper

##############################################################
# Source: device/intel/mixins/groups/security_assist/true/product.mk
##############################################################
# Intel Security Assist
PRODUCT_PACKAGES += \
        IntelSecurityAssist
PRODUCT_PACKAGES_ENG += \
        IntelSecurityAssistTest


##############################################################
# Source: device/intel/mixins/groups/libiha/true/product.mk
##############################################################
#Identity Protection Technology (IPT)
PRODUCT_PACKAGES += \
    libiha \
    epid_certificates \
    SepService

PRODUCT_PACKAGES_DEBUG += \
    TXEI_TEST TXEI_SEC_TOOLS
##############################################################
# Source: device/intel/mixins/groups/hw-keystore/txei/product.mk
##############################################################
PRODUCT_PACKAGES += \
	keystore.${TARGET_BOARD_PLATFORM} \
	keymaster_meid

##############################################################
# Source: device/intel/mixins/groups/hdcpd/true/product.mk
##############################################################
# Enable media content protection services

# HDCP Daemon
PRODUCT_PACKAGES += hdcpd
##############################################################
# Source: device/intel/mixins/groups/widevine/true/product.mk
##############################################################
#enable Widevine drm
PRODUCT_PROPERTY_OVERRIDES += drm.service.enabled=true

PRODUCT_COPY_FILES += device/intel/common/media/mfx_omxil_core_widevine.conf:system/etc/mfx_omxil_core.conf

# There is an additional dependency on hdcpd that should be controlled
# through the content-protection mixin

PRODUCT_PACKAGES += com.google.widevine.software.drm.xml \
    com.google.widevine.software.drm \
    libdrmwvmplugin \
    libwvm \
    libdrmdecrypt \
    libWVStreamControlAPI_L1 \
    libwvdrm_L1

PRODUCT_PACKAGES_ENG += WidevineSamplePlayer

# WV Modular
PRODUCT_PACKAGES += libwvdrmengine

PRODUCT_PACKAGES_ENG += ExoPlayerDemo

PRODUCT_PACKAGES += liboemcrypto

PRODUCT_PACKAGES += libmeimm libsecmem

BOARD_WIDEVINE_OEMCRYPTO_LEVEL := 1
##############################################################
# Source: device/intel/mixins/groups/release/true/product.mk
##############################################################
#
# Include generic build number for Intel devices
#
-include device/intel/common/build_number.mk
##############################################################
# Source: device/intel/mixins/groups/intel_prop/true/product.mk
##############################################################
PRODUCT_PACKAGES += intel_prop

PRODUCT_COPY_FILES += $(LOCAL_PATH)/../intel_prop.cfg:root/intel_prop.cfg
##############################################################
# Source: device/intel/mixins/groups/passpoint/true/product.mk
##############################################################
# Passpoint
PRODUCT_PACKAGES += \
    passpoint_specific
INTEL_PASSPOINT := true
##############################################################
# Source: device/intel/mixins/groups/vpp/isv/product.mk
##############################################################
# libisv
PRODUCT_PACKAGES += \
    libisv_omx_core \
    libisv

# isv settings
PRODUCT_PACKAGES += \
    VppSettings

# extmode - Intel video extended mode

# copy permission files
PRODUCT_COPY_FILES += \
    vendor/intel/hardware/libmedia_utils/ISV/display/v1/com.intel.extmode.xml:system/etc/permissions/com.intel.extmode.xml

PRODUCT_PACKAGES += \
    libextmodejni \
    com.intel.extmode
##############################################################
# Source: device/intel/mixins/groups/pstore/ram_pram/product.mk
##############################################################
PRODUCT_PACKAGES += \
    pstore-clean

$(call inherit-product, $(SRC_TARGET_DIR)/product/aosp_base.mk)

##############################################################
# Source: device/intel/mixins/groups/efiprop/used/product.mk
##############################################################
ifeq ($(TARGET_BUILD_VARIANT),user)
# For security concerns, the software scalability based on EFI
# variable is disabled on USER build.  Device MUST statically choose
# its configuration.
else
PRODUCT_PACKAGES += \
        efiprop
endif
##############################################################
# Source: device/intel/mixins/groups/memtrack/true/product.mk
##############################################################
# memtrack HAL
PRODUCT_PACKAGES += \
        memtrack.$(TARGET_BOARD_PLATFORM)
##############################################################
# Source: device/intel/mixins/groups/platformxml/true/product.mk
##############################################################
PRODUCT_COPY_FILES += $(LOCAL_PATH)/platform.xml:system/etc/sysconfig/platform.xml
##############################################################
# Source: device/intel/mixins/groups/cellcoex/true/product.mk
##############################################################
PRODUCT_PACKAGES += CellCoexApp
##############################################################
# Source: device/intel/mixins/groups/videocme/gen/product.mk
##############################################################
#WebRTC library and reference app
PRODUCT_PACKAGES += videoP2P \
    libwebrtc-video-p2p-jni \
    libwebrtc_full \
    libjingle_full \
    libjingle_peerconnection_so

PRODUCT_PACKAGES += AppRTC
PRODUCT_PACKAGES_DEBUG += WebRTCDemo
# cve video
PRODUCT_PACKAGES += \
    libvideocme-server \
    com.intel.ir94.videocme \
    com.intel.ir94.videocme.xml \
    libvideocme-jni \
    com.intel.rcs.vsh.vcme
##############################################################
# Source: device/intel/mixins/groups/mediaserver-radio/true/product.mk
##############################################################
PRODUCT_PACKAGES += mediaserver-radio
##############################################################
# Source: device/intel/mixins/groups/battery-config/dynamic/product.mk
##############################################################
ifeq ($(TARGET_BUILD_VARIANT),user)
# For security concerns, the software scalability based on EFI
# variable is disabled on USER build.
else
PRODUCT_COPY_FILES += device/intel/common/battery-config/init.battery-config.rc:root/init.battery-config.rc
BOARD_FLASHFILES += device/intel/common/battery-config/oemvars/oemvar-fake-battery-config.txt:oemvar-fake-battery-config.txt \
		    device/intel/common/battery-config/oemvars/oemvar-no-fake-battery-config.txt:oemvar-no-fake-battery-config.txt
endif
##############################################################
# Source: device/intel/mixins/groups/hdmi_settings/true/product.mk
##############################################################
PRODUCT_PACKAGES += HdmiSettings
DEVICE_PACKAGE_OVERLAYS += device/intel/common/overlays_hdmisettings
##############################################################
# Source: device/intel/mixins/groups/art-config/default/product.mk
##############################################################
# This is needed to enable silver art optimizer.
# This will build the plugins/libart-extension.so library,  which is dynamically loaded by
# AOSP and contains Intel optimizations to the compiler.
PRODUCT_PACKAGES += libart-extension
##############################################################
# Source: device/intel/mixins/groups/debug-kernel/default/product.mk
##############################################################
ifneq ($(TARGET_BUILD_VARIANT),user)
PRODUCT_COPY_FILES += device/intel/common/debug/init.kernel.rc:root/init.kernel.rc
endif
##############################################################
# Source: device/intel/mixins/groups/feature_config/default/product.mk
##############################################################
PRODUCT_PACKAGES += \
    com.intel.config \
    com.intel.config.xml
# ------------------ END MIX-IN DEFINITIONS ------------------
