/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SensorCaliJNI */

#ifndef _Included_SensorCaliJNI
#define _Included_SensorCaliJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SensorCaliJNI
 * Method:    setAGMStepA
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SensorCaliJNI_setAGMStepA
  (JNIEnv *, jobject, jint);

/*
 * Class:     SensorCaliJNI
 * Method:    setAGMStepB
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SensorCaliJNI_setAGMStepB
  (JNIEnv *, jobject, jint);

/*
 * Class:     SensorCaliJNI
 * Method:    setAGMStepC
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SensorCaliJNI_setAGMStepC
  (JNIEnv *, jobject, jint);

/*
 * Class:     SensorCaliJNI
 * Method:    setAGMStepD
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SensorCaliJNI_setAGMStepD
  (JNIEnv *, jobject, jint);

/*
 * Class:     SensorCaliJNI
 * Method:    setAGMStepE
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SensorCaliJNI_setAGMStepE
  (JNIEnv *, jobject, jint);

/*
 * Class:     SensorCaliJNI
 * Method:    setAGMStepF
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SensorCaliJNI_setAGMStepF
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
