#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_MSG2XXX_v3_10) += msg2133_ts.o
msg2133_ts-objs := mstar_drv_sprd.o
msg2133_ts-objs += mstar_drv_common.o
msg2133_ts-objs += mstar_drv_utility_adaption.o
msg2133_ts-objs += mstar_drv_fw_control.o
msg2133_ts-objs += mstar_drv_mp_test.o
msg2133_ts-objs += mstar_drv_ic_fw_porting_layer.o
msg2133_ts-objs += mstar_drv_main.o
msg2133_ts-objs += mstar_drv_platform_interface.o
msg2133_ts-objs += mstar_drv_platform_porting_layer.o
msg2133_ts-objs += mstar_drv_hotknot_queue.o
# msg2133_ts-objs += mstar_drv_qcom.o
msg2133_ts-objs += mstar_drv_hotknot.o
msg2133_ts-objs += mstar_drv_jni_interface.o
